name: Wiki Content Sync

on:
  push:
    branches:
      - main
    paths:
      - "docs/wiki/**"
  repository_dispatch:
    types: [docs]
  workflow_dispatch:
  gollum:

env:
  GIT_AUTHOR_NAME: GitHub Action
  GIT_AUTHOR_EMAIL: action@github.com
  SYNC_CHANGES_REPO_NAME: docs-sync

jobs:
  sync-content-to-wiki:
    if: always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && github.event_name != 'gollum'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync docs folder to wiki
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_SYNC_SECRET }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}

  job-sync-wiki-to-docs:
    if: github.event_name == 'gollum'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WIKI_SYNC_SECRET }}
          ref: ${{ github.event.repository.default_branch }}
      - name: Ensure Wiki Exists Before Syncing
        id: check_home
        run: |
          if [ ! -f "docs/wiki/Home.md" ]; then
            echo "Wiki Home.md does not exist in docs/wiki, skipping sync."
            exit 1
          fi
      - name: Create branch first
        run: git checkout -b $SYNC_CHANGES_REPO_NAME
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.WIKI_SYNC_SECRET }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: ${{ env.SYNC_CHANGES_REPO_NAME }}
      - name: Create pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.SYNC_CHANGES_REPO_NAME }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Chore] - Syncing Wiki changes in ${{ env.SYNC_CHANGES_REPO_NAME }} into default branch"
          pr_body: "This PR syncs the repository's wiki with the main docs."
          pr_label: "docs,automation"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.WIKI_SYNC_SECRET }}
